import { pgTable, serial, text, timestamp, boolean } from 'drizzle-orm/pg-core';

export const cadets = pgTable('cadets', {
  id: serial('id').primaryKey(),
  created_at: timestamp('created_at').defaultNow().notNull(),
  cadetName: text('cadet_name').notNull(),
  fatherName: text('father_name').notNull(),
  motherName: text('mother_name'),
  educationQualification: text('education_qualification').notNull(),
  dateOfBirth: timestamp('date_of_birth').notNull(),
  gender: text('gender').notNull(),
  mobileNo: text('mobile_no').notNull(),
  email: text('email').notNull(),
  bloodGroup: text('blood_group').notNull(),
  nationality: text('nationality'),
  permanentAddress: text('permanent_address'),
  interMarksDiploma: text('inter_marks_diploma'),
  identificationMarks: text('identification_marks'),
  medicalComplaint: text('medical_complaint'),
  nokName: text('nok_name'),
  nokRelationship: text('nok_relationship'),
  nokContactNumber: text('nok_contact_number'),
  nokAddress: text('nok_address'),
  extraCurricularActivity: text('extra_curricular_activity'),
  achievements: text('achievements'),
  criminalCourt: boolean('criminal_court'),
  criminalCourtDetails: text('criminal_court_details'),
  willingMilitaryTraining: boolean('willing_military_training'),
  willingServeNcc: boolean('willing_serve_ncc'),
  previouslyAppliedEnrollment: boolean('previously_applied_enrollment'),
  dismissedFromNccTaAf: boolean('dismissed_from_ncc_ta_af'),
  wingType: text('wing_type').notNull(),
  aadharNumber: text('aadhar_number'),
  aadharNumberFather: text('aadhar_number_father'),
  aadharNumberMother: text('aadhar_number_mother'),
  bankAccount: text('bank_account'),
  ifscNo: text('ifsc_no'),
  branchName: text('branch_name'),
  apparId: text('appar_id'),
  category: text('category').notNull(),
  regimentalNo: text('regimental_no'),
  campsAttendedWithDates: text('camps_attended'),
  nationalCampsAttendedWithDates: text('national_camps_attended')
});